<?php
/**
 * REST API Hardening
 *
 * Blocks unauthenticated order creation via WooCommerce REST/Store API.
 *
 * @package WC_Antifraud
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class WCAF_REST_Hardening {

	/**
	 * Error code returned when this class refuses a request. The settings
	 * self-test looks for it to tell this plugin's rejection apart from
	 * WooCommerce's own nonce check.
	 */
	const ERROR_CODE = 'wcaf_rest_forbidden';

	public static function init() {
		$opts = WCAF_Helpers::get_options();
		if ( empty( $opts['enable_rest_hardening'] ) ) {
			return;
		}
		add_filter( 'rest_pre_dispatch', [ __CLASS__, 'block_unauthenticated_order_creation' ], 10, 3 );
	}

	/**
	 * Block unauthenticated POST/PUT to order-creation endpoints
	 *
	 * @param mixed           $result
	 * @param WP_REST_Server  $server
	 * @param WP_REST_Request $request
	 * @return mixed|WP_Error
	 */
	public static function block_unauthenticated_order_creation( $result, $server, $request ) {
		$method = $request->get_method();
		if ( ! in_array( $method, [ 'POST', 'PUT' ], true ) ) {
			return $result;
		}

		$route          = $request->get_route();
		$blocked_routes = [
			'#^/wc/v[1-3]/orders/?$#',
			'#^/wc/store/v1/checkout/?$#',
			'#^/wc/store/checkout/?$#',
		];

		$is_blocked = false;
		foreach ( $blocked_routes as $pattern ) {
			if ( preg_match( $pattern, $route ) ) {
				$is_blocked = true;
				break;
			}
		}

		if ( ! $is_blocked ) {
			return $result;
		}

		$opts = WCAF_Helpers::get_options();
		$ip   = WCAF_Helpers::get_client_ip();

		// Allowlisted IPs (headless front ends, staging) bypass everything.
		if ( $ip && WCAF_Helpers::is_ip_allowed( $ip, $opts ) ) {
			return $result;
		}

		// Temporarily banned IPs get nothing, whatever credentials they carry.
		if ( $ip && WCAF_IP_Bans::is_banned( $ip ) ) {
			error_log( sprintf( 'WC Antifraud: Blocked REST API order creation from banned IP. Route: %s, IP: %s', $route, $ip ) );
			return new WP_Error( self::ERROR_CODE, __( 'Order creation via REST API is not permitted.', 'wc-antifraud' ), [ 'status' => 403 ] );
		}

		// Allow authenticated admin users
		if ( current_user_can( 'manage_woocommerce' ) ) {
			return $result;
		}

		// Allow WC API key auth
		if ( ! empty( $request->get_param( 'consumer_key' ) ) ) {
			return $result;
		}

		// Allow OAuth / Bearer auth (WC REST API, webhooks)
		if ( ! empty( $request->get_header( 'authorization' ) ) ) {
			return $result;
		}

		// Allow WooCommerce Store API requests with a VALID nonce.
		// Legitimate Block Checkout sends a nonce generated by WC's JS.
		// Bots that POST directly will have no nonce or an invalid one.
		$nonce = $request->get_header( 'nonce' );
		if ( empty( $nonce ) ) {
			$nonce = $request->get_header( 'x-wc-store-api-nonce' );
		}

		if ( ! empty( $nonce ) && wp_verify_nonce( $nonce, 'wc_store_api' ) ) {
			return $result;
		}

		error_log( sprintf( 'WC Antifraud: Blocked REST API order creation. Route: %s, IP: %s', $route, $ip ?: 'unknown' ) );

		return new WP_Error( self::ERROR_CODE, __( 'Order creation via REST API is not permitted.', 'wc-antifraud' ), [ 'status' => 403 ] );
	}
}
