<?php
/**
 * Email Alert Handler
 *
 * @package WC_Antifraud
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class WCAF_Email_Alerts {

	/**
	 * Send fraud alert email
	 *
	 * @param WC_Order $order
	 * @param array    $reasons
	 * @param array    $opts
	 * @return bool
	 */
	public static function send_alert( $order, $reasons, $opts ) {
		$addresses = WCAF_Helpers::sanitize_email_list( $opts['email_recipients'] ?? '' );
		if ( empty( $addresses ) ) {
			return false;
		}

		$site    = get_bloginfo( 'name' );
		$subject = sprintf( '[%s — Antifraud] Suspicious order #%d', $site, $order->get_id() );

		$body   = [];
		$body[] = __( 'A suspicious order has been detected and automatically flagged.', 'wc-antifraud' );
		$body[] = '';
		$body[] = __( 'ORDER DETAILS:', 'wc-antifraud' );
		$body[] = sprintf( 'Order #: %d', $order->get_id() );
		$body[] = sprintf( 'Total: %s', $order->get_formatted_order_total() );
		$body[] = sprintf( 'Status: %s', wc_get_order_status_name( $order->get_status() ) );
		$body[] = sprintf( 'Date: %s', $order->get_date_created()->date_i18n( wc_date_format() . ' ' . wc_time_format() ) );
		$body[] = '';
		$body[] = __( 'BILLING INFORMATION:', 'wc-antifraud' );
		$body[] = sprintf( 'Name: %s %s', $order->get_billing_first_name(), $order->get_billing_last_name() );
		$body[] = sprintf( 'Email: %s', $order->get_billing_email() );
		$body[] = sprintf( 'Phone: %s', $order->get_billing_phone() );
		$body[] = '';
		$body[] = __( 'FRAUD INDICATORS:', 'wc-antifraud' );
		$body[] = implode( ', ', $reasons );
		$body[] = '';
		$body[] = __( 'ORDER ITEMS:', 'wc-antifraud' );
		foreach ( $order->get_items() as $item ) {
			$body[] = sprintf( '- %s x %s', $item->get_name(), $item->get_quantity() );
		}
		$body[] = '';
		$body[] = __( 'ACTIONS:', 'wc-antifraud' );
		$body[] = sprintf( 'View in admin: %s', admin_url( 'post.php?post=' . $order->get_id() . '&action=edit' ) );
		$body[] = '';
		$body[] = '---';
		$body[] = sprintf( __( 'Generated by WC Antifraud on %s', 'wc-antifraud' ), $site );

		$headers = [
			'Content-Type: text/plain; charset=UTF-8',
			sprintf( 'From: %s <%s>', $site, get_option( 'admin_email' ) ),
		];

		$sent = true;
		foreach ( $addresses as $to ) {
			if ( ! wp_mail( $to, $subject, implode( "\n", $body ), $headers ) ) {
				$sent = false;
			}
		}
		return $sent;
	}
}
