<?php
/**
 * Email Alert Handler
 *
 * @package WC_Antifraud
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class WCAF_Email_Alerts {

	/**
	 * Send fraud alert email
	 *
	 * @param WC_Order $order
	 * @param array    $reasons
	 * @param array    $opts
	 * @param bool     $monitor True when the order was only flagged (monitor mode),
	 *                          false when it was cancelled as fraud.
	 * @return bool
	 */
	public static function send_alert( $order, $reasons, $opts, $monitor = false ) {
		$addresses = WCAF_Helpers::sanitize_email_list( $opts['email_recipients'] ?? '' );
		if ( empty( $addresses ) ) {
			return false;
		}

		$site    = get_bloginfo( 'name' );
		$subject = $monitor
			? sprintf( '[%s — Antifraud] Suspicious order #%d flagged for review (monitor mode)', $site, $order->get_id() )
			: sprintf( '[%s — Antifraud] Suspicious order #%d', $site, $order->get_id() );

		$body   = [];
		$body[] = $monitor
			? __( 'A suspicious order has been detected. Monitor mode is on, so the order was flagged for review and its status was NOT changed.', 'wc-antifraud' )
			: __( 'A suspicious order has been detected and automatically flagged.', 'wc-antifraud' );
		$body[] = '';
		$body[] = __( 'ORDER DETAILS:', 'wc-antifraud' );
		$body[] = sprintf( 'Order #: %d — %s', $order->get_id(), admin_url( 'post.php?post=' . $order->get_id() . '&action=edit' ) );
		$body[] = sprintf( 'Total: %s', html_entity_decode( wp_strip_all_tags( $order->get_formatted_order_total() ), ENT_QUOTES, 'UTF-8' ) );
		$body[] = sprintf( 'Status: %s', wc_get_order_status_name( $order->get_status() ) );
		$body[] = sprintf( 'Date: %s', $order->get_date_created()->date_i18n( wc_date_format() . ' ' . wc_time_format() ) );
		$body[] = '';
		$body[] = __( 'BILLING INFORMATION:', 'wc-antifraud' );
		$body[] = sprintf( 'Name: %s %s', $order->get_billing_first_name(), $order->get_billing_last_name() );
		$body[] = sprintf( 'Email: %s', $order->get_billing_email() );
		$body[] = sprintf( 'Phone: %s', $order->get_billing_phone() );
		$body[] = sprintf( 'IP: %s', $order->get_customer_ip_address() ?: '-' );
		$body[] = '';
		$body[] = __( 'FRAUD INDICATORS:', 'wc-antifraud' );
		$body[] = implode( ', ', $reasons );
		$body[] = '';
		$body[] = __( 'ORDER ITEMS:', 'wc-antifraud' );
		foreach ( $order->get_items() as $item ) {
			$body[] = sprintf( '- %s x %s', $item->get_name(), $item->get_quantity() );
		}
		$body[] = '';
		$body[] = __( 'ACTIONS:', 'wc-antifraud' );
		$body[] = sprintf( 'View in admin: %s', admin_url( 'post.php?post=' . $order->get_id() . '&action=edit' ) );
		if ( $monitor ) {
			$body[] = __( 'To cancel it as fraud, use "Change status to Fraud" on the Orders list, or switch Detection mode back to Block.', 'wc-antifraud' );
		}
		$body[] = '';
		$body[] = '---';
		$body[] = sprintf( __( 'Generated by WC Antifraud on %s', 'wc-antifraud' ), $site );

		$headers = [
			'Content-Type: text/plain; charset=UTF-8',
			sprintf( 'From: %s <%s>', $site, get_option( 'admin_email' ) ),
		];

		$sent = true;
		foreach ( $addresses as $to ) {
			if ( ! wp_mail( $to, $subject, implode( "\n", $body ), $headers ) ) {
				$sent = false;
			}
		}
		return $sent;
	}
}
